services:
  app:
    container_name: redirect-app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - redirect:/redirect
    restart: unless-stopped
    environment:
      - ORIGIN=https://redirect-gui.shmee.codes
    networks:
      - apps
  caddy:
    container_name: redirect-caddy
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./caddy/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - apps

name: redirect

volumes:
  redirect:
  caddy_data:
  caddy_config:

networks:
  apps:
    external: true